DROP SCHEMA IF EXISTS `IFC`;
CREATE SCHEMA IF NOT EXISTS `IFC` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE IFC;

CREATE TABLE IF NOT EXISTS temp_table (
	temp_id    INT UNSIGNED NOT NULL AUTO_INCREMENT,
	temp_value FLOAT DEFAULT 0.00,
	PRIMARY KEY (temp_id)
);